### ISSUE TITLE
Docker PORT 충돌

### ISSUE THREAD

**Issue by seilylook** [seilylook/Spark_on_Local_Kubernetes#1]
## 에러

Error response from daemon: Ports are not available: exposing port TCP 0.0.0.0:7000 -> 0.0.0.0:0: listen tcp 0.0.0.0:7000: bind: address already in use

## 해결

```
lsof -i :7000

kill -9 PID
```

하지만 port를 사용중인 서비스를 kill 했는데도, 없어지지 않고 다른 PID로 서비스가 계속 7000 PORT를 사용중이었다. 원인을 찾던 중에 발견한 것은 `Macbook의 Airdrop` 서비스가 사용하는 PORT 번호가 7000인 것을 확인했다. 이를 해결하기 위해 기존 docker service의 port 번호를 변경하려 한다.

**Comment by seilylook** [comment]
```
  spark-master:
    image: my-own-spark:3.4.0
    ports:
      - "32766:8080"
      - "32765:7077"

  spark-worker-a:
    image: my-own-spark:3.4.0
    ports:
      - "32764:8080"
      - "32763:8081"
      
   spark-worker-b:
    image: my-own-spark:3.4.0
    ports:
      - "32762:8080"
      - "32761:8081"
  ```
